; Hardware ports and the resident RAM ABI shared with the 68000.
zROMBankLow:                 equ     1C00h
zROMBankHigh:                equ     1C01h
zLoadedDataTable:            equ     1C02h
zTimerAValue:                equ     1C04h
zTimerBValue:                equ     1C06h
zUpdatePending:              equ     1C07h
zLoadedSFXCount:             equ     1C08h
zMusicCommand:               equ     1C09h
zSFXCommand0:                equ     1C0Ah
zSFXCommand1:                equ     1C0Bh
zSFXCommand2:                equ     1C0Ch
zFadeSteps:                  equ     1C0Dh
zFadeDelay:                  equ     1C0Eh
zFadeCounter:                equ     1C0Fh
zPauseFlag:                  equ     1C10h
zChannelOverride:            equ     1C11h
zFM3Mode:                    equ     1C12h
zTempoCounter:               equ     1C13h
zTempoReload:                equ     1C14h
zCurrentPriority:            equ     1C15h
zCoordFlagValue:             equ     1C16h
zRandomValue:                equ     1C17h
zCurrentSFXPriority:         equ     1C18h
zTrackContext:               equ     1C19h
zFM3OperatorFrequency0:      equ     1C1Ah
zFM3OperatorFrequency1:      equ     1C22h
zFM3OperatorFrequency2:      equ     1C2Ah
zCurrentTrackIndex:          equ     1C32h
zTrackHeaderCursor:          equ     1C33h
zTrackInitCursor:            equ     1C35h
zMusicVoiceTable:            equ     1C37h
zSFXVoiceTable:              equ     1C39h
zSFXTempoDivider:            equ     1C3Bh
zMusicFMTrack0:              equ     1C40h
zMusicTrackTempoDivider:     equ     1C42h
zMusicFMTrack0Duration:      equ     1C4Bh
zMusicFMTrack1:              equ     1C70h
zMusicFMTrack4:              equ     1D00h
zMusicFMTrack5:              equ     1D30h
zDACTrack:                   equ     1D60h
zDACTranspose:               equ     1D65h
zDACVolume:                  equ     1D66h
zDACVolumeEnvelope:          equ     1D68h
zMusicPSGTrack0:             equ     1D90h
zMusicPSGTrack1:             equ     1DC0h
zMusicPSGTrack2:             equ     1DF0h
zSpecialSFXTrack0:           equ     1E20h
zSpecialSFXTrack1:           equ     1E50h
zSFXTrack0:                  equ     1E80h
zSFXTrack1:                  equ     1EB0h
zSFXTrack2:                  equ     1EE0h
zSFXTrack3:                  equ     1F10h
zSFXTrack4:                  equ     1F40h
zSFXTrack5:                  equ     1F70h
zStack:                      equ     1FFDh
zInterruptCountdown:         equ     1FFFh
zYM2612_A0:                  equ     4000h
zYM2612_D0:                  equ     4001h
zYM2612_A1:                  equ     4002h
zYM2612_D1:                  equ     4003h
zBankRegister:               equ     6000h
zPSG:                        equ     7F11h
zROMWindow:                  equ     8000h

zTrackSize:                 equ     30h
zCoordFlagFirst:            equ     0E0h

; One channel occupies 30h bytes. Names below are the fields established
; by all reads/writes in the driver; the final eight bytes are reused as
; loop counters, the sequence-call stack, and an SFX voice-table pointer.
zTrackFlags:                 equ     0
zTrackChannel:               equ     1
zTrackDurationScale:         equ     2
zTrackData:                  equ     3
zTrackTranspose:             equ     5
zTrackVolume:                equ     6
zTrackPitchEnvelope:         equ     7
zTrackVolumeEnvelope:        equ     8
zTrackStackPointer:          equ     9
zTrackVoiceControl:          equ     0Ah
zTrackDuration:              equ     0Bh
zTrackSavedDuration:         equ     0Ch
zTrackFrequency:             equ     0Dh
zTrackVoiceIndex:            equ     0Fh
zTrackFrequencyOffset:       equ     10h
zTrackModulationDelay:       equ     11h
zTrackModulationSpeed:       equ     12h
zTrackModulationStep:        equ     13h
zTrackModulationSteps:       equ     14h
zTrackModulationSpeedReload: equ     15h
zTrackModulationSpeedCounter: equ     16h
zTrackPSGEnvelopeCursor:     equ     17h
zTrackFMEnvelope:            equ     18h
zTrackFMEnvelopeMask:        equ     19h
zTrackPSGNoise:              equ     1Ah
zTrackFMAlgorithm:           equ     1Bh
zTrackFMLevels:              equ     1Ch
zTrackNoteFillCounter:       equ     1Eh
zTrackNoteFillReload:        equ     1Fh
zTrackPitchEnvelopeData:     equ     20h
zTrackPitchEnvelopeValue:    equ     22h
zTrackPitchEnvelopeDelay:    equ     24h
zTrackPitchEnvelopeCursor:   equ     25h
zTrackPitchEnvelopeStep:     equ     26h
zTrackPitchEnvelopeStepCounter: equ     27h
zTrackLoopCounters:          equ     28h
zTrackVoiceTable:            equ     2Ah
